version: "3"
services:
  redisdb:
    container_name: redisdb
    hostname: redis
    image: redis
    volumes:
      - /cache:/data
    ports:
      - "6379:6379"


  fullstack-cms:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
    depends_on:
      - redisdb
volumes:
  cache:

   
